import Link from "next/link";
import { useEffect, useState } from "react";
import { IoIosArrowBack } from "react-icons/io";
import { v4 as uuid } from "uuid";
import useCreateDate from "../components/useCreateDate";
import { useRouter } from "next/router";
import { useNoteContext } from "@/components/NoteContext";
import Head from "next/head";

const CreateNote = () => {
  const {
    title,
    setTitle,
    details,
    setDetails,
    note,
    setNote,
    handleSubmit,
    noEmailPassword,
  } = useNoteContext();
  return (
    <>
      <Head>
        <title>Notes App | Create-note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen ">
        <div className=" md:w-2/3 mx-auto text-white h-full  p-4  ">
          <header className="w-full flex items-center justify-between ">
            <Link href="/">
              <button className="text-xl bg-purple-700 p-2 rounded-md">
                <IoIosArrowBack />
              </button>
            </Link>
            <button
              className="bg-purple-700  py-2 px-4 rounded-md text-sm font-medium "
              onClick={handleSubmit}
            >
              Save
            </button>
          </header>
          {!title ||
            (!details && (
              <p className="text-red-600 font-bold ">{noEmailPassword}</p>
            ))}
          <form className="flex flex-col gap-4 mt-8">
            <input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              type="text"
              placeholder="Title"
              autoFocus
              className="bg-transparent border-none outline-none text-3xl text-gray-200"
            />
            <textarea
              value={details}
              onChange={(e) => setDetails(e.target.value)}
              rows="28"
              placeholder="Note Details..."
              className="bg-transparent border-none outline-none text-sm text-gray-200"
            ></textarea>
          </form>
        </div>
      </main>
    </>
  );
};

export default CreateNote;
